---
- hosts: webservers
  tasks:
  - name: Install nginx  (state=present is optional)
    apt:
      name: nginx
      state: present  
  - name: Create a directory if it does not exist
    file:
      path: /var/www/tutorial
      state: directory
      mode: '0755'
  - name: copy index.html files
    copy:
      src: index.html
      dest: /var/www/tutorial/index.html
    notify: restart service nginx  
 #- name: Create a directory if it does not exist
 #   file:
 #    path: /etc/nginx/sites-enabled/
 #     state: directory
 #    mode: '0755'
  - name: copy tutorial files
    copy:
      src: tutorial
      dest: /etc/nginx/sites-enabled/tutorial 
    notify: restart service nginx  
  handlers: 
    - name: restart service nginx
      service:
         name: nginx
         state: started

